# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=20)),
                ('beginTime', models.DateTimeField(verbose_name='Start Time')),
                ('endTime', models.DateTimeField(verbose_name='End Time')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('userName', models.CharField(max_length=20)),
                ('eMail', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Event')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.User')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('streetAddress', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zipCode', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(default=0)),
                ('contact', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='venueId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Venue'),
        ),
    ]
