# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20160829_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='full',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='tickets_sold',
            field=models.IntegerField(default=0),
        ),
    ]
